package com.conciergeiq.agent;

import com.conciergeiq.dto.ChatResponseDto.ProposedActivity;
import com.conciergeiq.dto.ChatResponseDto.RecommendationCard;
import lombok.Builder;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;

@Data
@Builder
public class AgentState {
    private String userQuery;
    private Long userId;
    
    // Extracted by Input Agent
    private String location;
    private Integer budget;
    private Double userLat;
    private Double userLng;
    
    // Generated by Itinerary & Planner Agent
    private String tripTitle;
    @Builder.Default
    private List<ProposedActivity> activities = new ArrayList<>();
    @Builder.Default
    private List<RecommendationCard> recommendations = new ArrayList<>();
    
    // Executed by Booking Agent
    @Builder.Default
    private List<String> bookingConfirmationIds = new ArrayList<>();
    
    // Trace execution logs of agents working together (simulating LangGraph edges)
    @Builder.Default
    private List<String> executionLogs = new ArrayList<>();

    public void addLog(String agentName, String message) {
        this.executionLogs.add(String.format("[%s]: %s", agentName, message));
    }
}
